import { type Wallpaper, type Category } from './types.ts';

const R2_BASE_URL = "https://cdn.walzoo.com";

export const SUB_CATEGORIES = [
  'Space',
  'Nature',
  'Cities & Landmarks',
  'Abstract',
  'Minimalist',
  'Technology',
  'Digital Art',
  'Gaming',
  'Animals',
  'Cars',
  'Seasons',
  'Sports',
  'Quotes',
  'Anime',
  'Culture',
  'Kids'
];

// Data Wipe: Removed all existing image entries to start fresh with new 4K strategy.
export const MY_IMAGES: Wallpaper[] = [
  {
    id: 1,
    slug: "aerial-beach-palm-trees-turquoise-water",
    title: "Aerial Beach Palm Trees",
    description: "A stunning aerial view of a tropical beach with palm trees and turquoise water. High-quality 4K Nature wallpaper.",
    imageUrl: `${R2_BASE_URL}/Desktop/Nature/aerial-beach-palm-trees-turquoise-water.webp`,
    category: 'Desktop',
    subCategory: 'Nature',
    width: 3840,
    height: 2160,
    extension: 'webp'
  },
  {
    id: 2,
    slug: "saturn-rings-black-and-white-minimalist",
    title: "Saturn Rings Minimalist",
    description: "A striking black and white minimalist view of Saturn's iconic rings in deep space. Perfect for clean desktop setups.",
    imageUrl: `${R2_BASE_URL}/Desktop/Space/saturn-rings-black-and-white-minimalist.webp`,
    category: 'Desktop',
    subCategory: 'Space',
    width: 3840,
    height: 2160,
    extension: 'webp'
  },
  {
    id: 3,
    slug: "blue-teal-slate-stone-wall-pattern",
    title: "Blue Teal Slate Stone",
    description: "An abstract and textured pattern of blue and teal slate stones, offering a rugged yet modern aesthetic for your phone.",
    imageUrl: `${R2_BASE_URL}/Phone/Abstract/blue-teal-slate-stone-wall-pattern.webp`,
    category: 'Phone',
    subCategory: 'Abstract',
    width: 1080,
    height: 2340,
    extension: 'webp'
  },
  {
    id: 4,
    slug: "eiffel-tower-paris-street-view",
    title: "Eiffel Tower Street View",
    description: "A classic street view of the Eiffel Tower in Paris, capturing the romantic atmosphere of the city in high resolution.",
    imageUrl: `${R2_BASE_URL}/Phone/Cities%20%26%20Landmarks/eiffel-tower-paris-street-view.webp`,
    category: 'Phone',
    subCategory: 'Cities & Landmarks',
    width: 1080,
    height: 2340,
    extension: 'webp'
  },
  {
    id: 5,
    slug: "classic-teal-stripe-pattern-linen",
    title: "Classic Teal Stripe Pattern",
    description: "A minimalist teal stripe pattern on a linen-like texture, ideal for a clean and professional tablet background.",
    imageUrl: `${R2_BASE_URL}/Tablet/Minimalist/classic-teal-stripe-pattern-linen.webp`,
    category: 'Tablet',
    subCategory: 'Minimalist',
    width: 2048,
    height: 2732,
    extension: 'webp'
  },
  {
    id: 6,
    slug: "cyber-circuit-cat-gold-lights",
    title: "Cyber Circuit Cat",
    description: "A futuristic digital cat design featuring glowing gold circuits and neon technology elements. 4K Tablet art.",
    imageUrl: `${R2_BASE_URL}/Tablet/Technology/cyber-circuit-cat-gold-lights.webp`,
    category: 'Tablet',
    subCategory: 'Technology',
    width: 2048,
    height: 2732,
    extension: 'webp'
  },
  {
    id: 7,
    slug: "neon-donuts-desert-night",
    title: "Neon Donuts Desert Night",
    description: "A vibrant digital art piece featuring neon donuts in a desert setting at night. Perfect for 4K desktop screens.",
    imageUrl: `${R2_BASE_URL}/Desktop/Digital%20Art/neon-donuts-to-go-desert-night.webp`,
    category: 'Desktop',
    subCategory: 'Digital Art',
    width: 3840,
    height: 2160,
    extension: 'webp'
  },
  {
    id: 8,
    slug: "neon-playstation-symbols",
    title: "Neon PlayStation Symbols",
    description: "Glowing neon PlayStation symbols set against a dark concrete wall, ideal for any gaming setup.",
    imageUrl: `${R2_BASE_URL}/Desktop/Gaming/neon-playstation-symbols-concrete-wall.webp`,
    category: 'Desktop',
    subCategory: 'Gaming',
    width: 3840,
    height: 2160,
    extension: 'webp'
  },
  {
    id: 9,
    slug: "penguin-iceberg-milky-way",
    title: "Penguin Iceberg Milky Way",
    description: "A majestic penguin standing on an iceberg under the Milky Way in Antarctica. Stunning phone wallpaper.",
    imageUrl: `${R2_BASE_URL}/Phone/Animals/penguin-iceberg-milky-way-antarctica.webp`,
    category: 'Phone',
    subCategory: 'Animals',
    width: 1080,
    height: 2340,
    extension: 'webp'
  },
  {
    id: 10,
    slug: "red-ferrari-autumn-reflection",
    title: "Red Ferrari Autumn Reflection",
    description: "A sleek red Ferrari in a showroom with beautiful autumn reflections. High-resolution car wallpaper for mobile.",
    imageUrl: `${R2_BASE_URL}/Phone/Cars/red-ferrari-showroom-autumn-reflection.webp`,
    category: 'Phone',
    subCategory: 'Cars',
    width: 1080,
    height: 2340,
    extension: 'webp'
  },
  {
    id: 11,
    slug: "autumn-leaves-sunset-forest",
    title: "Autumn Leaves Sunset Forest",
    description: "Golden autumn leaves and a serene forest path at sunset. A peaceful seasonal background for your tablet.",
    imageUrl: `${R2_BASE_URL}/Tablet/Seasons/autumn-leaves-sunset-forest-path.webp`,
    category: 'Tablet',
    subCategory: 'Seasons',
    width: 2048,
    height: 2732,
    extension: 'webp'
  },
  {
    id: 12,
    slug: "outdoor-basketball-court-night",
    title: "Outdoor Basketball Court Night",
    description: "An outdoor basketball court illuminated by moonlight at night. Dynamic sports theme for tablet screens.",
    imageUrl: `${R2_BASE_URL}/Tablet/Sports/outdoor-basketball-court-night-moonlight.webp`,
    category: 'Tablet',
    subCategory: 'Sports',
    width: 2048,
    height: 2732,
    extension: 'webp'
  },
  {
    id: 13,
    slug: "never-give-up-create-future",
    title: "Never Give Up Quote",
    description: "Inspirational 'Never Give Up' quote wallpaper for your desktop. High-quality 4K typography.",
    imageUrl: `${R2_BASE_URL}/Desktop/Quotes/never-give-up-create-your-own-future.webp`,
    category: 'Desktop',
    subCategory: 'Quotes',
    width: 3840,
    height: 2160,
    extension: 'webp'
  },
  {
    id: 14,
    slug: "samurai-warrior-tall-grass",
    title: "Samurai Warrior in Tall Grass",
    description: "An epic anime-style samurai warrior standing in tall grass. Stunning 4K desktop background.",
    imageUrl: `${R2_BASE_URL}/Desktop/Anime/samurai-warrior-standing-in-tall-grass.webp`,
    category: 'Desktop',
    subCategory: 'Anime',
    width: 3840,
    height: 2160,
    extension: 'webp'
  },
  {
    id: 15,
    slug: "parthenon-acropolis-athens-sunset",
    title: "Parthenon Acropolis Sunset",
    description: "A breathtaking sunset view of the Parthenon in Athens. Historical culture wallpaper for phone.",
    imageUrl: `${R2_BASE_URL}/Phone/Culture/parthenon-acropolis-athens-sunset-view.webp`,
    category: 'Phone',
    subCategory: 'Culture',
    width: 1080,
    height: 2340,
    extension: 'webp'
  },
  {
    id: 16,
    slug: "cute-cartoon-cat-peace-sign",
    title: "Cute Cartoon Cat Peace Sign",
    description: "A cute grey cartoon cat showing a peace sign. Fun and playful wallpaper for kids' phones.",
    imageUrl: `${R2_BASE_URL}/Phone/Kids/cute-grey-cartoon-cat-peace-sign.webp`,
    category: 'Phone',
    subCategory: 'Kids',
    width: 1080,
    height: 2340,
    extension: 'webp'
  },
  {
    id: 17,
    slug: "mountain-cabin-lake-reflection",
    title: "Mountain Cabin Lake Reflection",
    description: "Serene mountain cabin with a perfect lake reflection in the Dolomites. Beautiful 4K Nature tablet wallpaper.",
    imageUrl: `${R2_BASE_URL}/Tablet/Nature/mountain-cabin-lake-reflection-dolomites.webp`,
    category: 'Tablet',
    subCategory: 'Nature',
    width: 2048,
    height: 2732,
    extension: 'webp'
  },
  {
    id: 18,
    slug: "saturn-rings-minimalist-bw",
    title: "Saturn Rings Minimalist B&W",
    description: "Minimalist black and white view of Saturn's rings in space. Clean aesthetic for tablet screens.",
    imageUrl: `${R2_BASE_URL}/Tablet/Space/saturn-rings-minimalist-bw-space.webp`,
    category: 'Tablet',
    subCategory: 'Space',
    width: 2048,
    height: 2732,
    extension: 'webp'
  },
  {
    id: 19,
    slug: "manhattan-bridge-skyline-reflection",
    title: "Manhattan Bridge Reflection",
    description: "Stunning 4K reflection of the Manhattan and Brooklyn Bridge skylines. Iconic city landmark wallpaper for desktop.",
    imageUrl: `${R2_BASE_URL}/Desktop/Cities%20%26%20Landmarks/manhattan-bridge-brooklyn-bridge-skyline-reflection.webp`,
    category: 'Desktop',
    subCategory: 'Cities & Landmarks',
    width: 3840,
    height: 2160,
    extension: 'webp'
  },
  {
    id: 20,
    slug: "abstract-acrylic-paint-swirls",
    title: "Abstract Acrylic Swirls",
    description: "Vibrant abstract acrylic paint swirls in blue, orange, and white. Modern 4K art for your desktop background.",
    imageUrl: `${R2_BASE_URL}/Desktop/Abstract/abstract-acrylic-paint-swirls-blue-orange-white.webp`,
    category: 'Desktop',
    subCategory: 'Abstract',
    width: 3840,
    height: 2160,
    extension: 'webp'
  },
  {
    id: 21,
    slug: "vertical-abstract-paint-splash",
    title: "Vertical Abstract Splash",
    description: "A clean and minimalist vertical abstract paint splash background for mobile. Features blue, orange, and white tones.",
    imageUrl: `${R2_BASE_URL}/Phone/Minimalist/vertical-abstract-paint-splash-blue-orange-white-background.webp`,
    category: 'Phone',
    subCategory: 'Minimalist',
    width: 1080,
    height: 2340,
    extension: 'webp'
  },
  {
    id: 22,
    slug: "neon-geometric-bokeh-lights",
    title: "Neon Geometric Bokeh",
    description: "Futuristic abstract bokeh lights with neon geometric lines. High-resolution technology theme for your phone.",
    imageUrl: `${R2_BASE_URL}/Phone/Technology/abstract-bokeh-lights-neon-geometric-lines-mobile.webp`,
    category: 'Phone',
    subCategory: 'Technology',
    width: 1080,
    height: 2340,
    extension: 'webp'
  },
  {
    id: 23,
    slug: "glowing-neon-glass-cubes",
    title: "Glowing Neon Glass Cubes",
    description: "Epic 3D abstract art of glowing neon glass cubes. Perfect gaming aesthetic for your tablet screen.",
    imageUrl: `${R2_BASE_URL}/Tablet/Gaming/glowing-neon-glass-cubes-3d-abstract-art-tablet.webp`,
    category: 'Tablet',
    subCategory: 'Gaming',
    width: 2048,
    height: 2732,
    extension: 'webp'
  },
  {
    id: 24,
    slug: "textured-geometric-paint-tiles",
    title: "Textured Geometric Tiles",
    description: "Artistic textured geometric paint tiles in vibrant orange and teal. Stylish digital art wallpaper for tablets.",
    imageUrl: `${R2_BASE_URL}/Tablet/Digital%20Art/textured-geometric-paint-tiles-orange-teal-tablet.webp`,
    category: 'Tablet',
    subCategory: 'Digital Art',
    width: 2048,
    height: 2732,
    extension: 'webp'
  },
  {
    id: 31,
    slug: "majestic-stallions-bw-portrait",
    title: "Majestic Stallions B&W",
    description: "A powerful black and white portrait of two wild stallions. High-definition 4K animal photography for desktop.",
    imageUrl: "https://cdn.walzoo.com/Desktop/Animals/black-and-white-stallions-portrait-minimalist-desktop.webp",
    category: 'Desktop',
    subCategory: 'Animals',
    width: 3840,
    height: 2160,
    extension: 'webp'
  },
  {
    id: 32,
    slug: "manhattan-skyline-river-reflection",
    title: "Manhattan River Skyline",
    description: "Breathtaking view of the Manhattan skyline reflecting in the East River at sunset. Premium 4K car-themed desktop backdrop.",
    imageUrl: "https://cdn.walzoo.com/Desktop/Cars/manhattan-bridge-skyline-reflection-east-river-desktop.jpg.webp",
    category: 'Desktop',
    subCategory: 'Cars',
    width: 3840,
    height: 2160,
    extension: 'webp'
  },
  {
    id: 33,
    slug: "colorful-boats-aerial-shore",
    title: "Aerial Shore Colorful Boats",
    description: "Symmetry of colorful wooden boats on a sandy shore seen from above. A beautiful seasons-themed phone wallpaper.",
    imageUrl: "https://cdn.walzoo.com/Phone/Seasons/aerial-view-colorful-wooden-boats-sandy-shore-mobile.webp",
    category: 'Phone',
    subCategory: 'Seasons',
    width: 1080,
    height: 2340,
    extension: 'webp'
  },
  {
    id: 34,
    slug: "aesthetic-basketball-hoop-moonlight",
    title: "Moonlight Basketball Aesthetic",
    description: "Glow of a basketball hoop against the night sky under bright moonlight. Moody sports aesthetic for mobile screens.",
    imageUrl: "https://cdn.walzoo.com/Phone/Sports/outdoor-basketball-hoop-night-moonlight-aesthetic-mobile.webp",
    category: 'Phone',
    subCategory: 'Sports',
    width: 1080,
    height: 2340,
    extension: 'webp'
  },
  {
    id: 35,
    slug: "soccer-action-watercolor-art",
    title: "Soccer Action Watercolor",
    description: "Artistic watercolor depiction of a soccer player in mid-kick. Dynamic action art for tablet displays.",
    imageUrl: "https://cdn.walzoo.com/Tablet/Anime/watercolor-soccer-player-kicking-ball-action-art-tablet.webp",
    category: 'Tablet',
    subCategory: 'Anime',
    width: 2048,
    height: 2732,
    extension: 'webp'
  },
  {
    id: 36,
    slug: "one-percent-better-daily-typography",
    title: "One Percent Better Quote",
    description: "Motivational quote 'One percent better every day' in clean minimalist typography. Inspiring tablet background.",
    imageUrl: "https://cdn.walzoo.com/Tablet/Quotes/one-percent-better-every-day-minimalist-typography-tablet.webp",
    category: 'Tablet',
    subCategory: 'Quotes',
    width: 2048,
    height: 2732,
    extension: 'webp'
  },
  {
    id: 37,
    slug: "flatiron-building-nyc-blue-bugatti",
    title: "NYC Flatiron & Blue Bugatti",
    description: "A striking view of the Flatiron building in NYC featuring a sleek blue Bugatti supercar. High-quality 4K culture wallpaper.",
    imageUrl: "https://cdn.walzoo.com/Desktop/Culture/flatiron-building-nyc-blue-bugatti-supercar-pc.webp",
    category: 'Desktop',
    subCategory: 'Culture',
    width: 3840,
    height: 2160,
    extension: 'webp'
  },
  {
    id: 38,
    slug: "tiger-panda-friends-birthday-party",
    title: "Tiger and Panda Party",
    description: "Cute cartoon tiger and panda best friends celebrating a birthday party. Fun and colorful 4K wallpaper for kids.",
    imageUrl: "https://cdn.walzoo.com/Desktop/Kids/cartoon-tiger-and-panda-best-friends-birthday-party-desktop.webp",
    category: 'Desktop',
    subCategory: 'Kids',
    width: 3840,
    height: 2160,
    extension: 'webp'
  },
  {
    id: 39,
    slug: "earth-from-space-night-lights-minimal",
    title: "Earth Night Lights Minimalist",
    description: "A minimalist view of Earth from space at night, showing city lights glowing against the darkness. Beautiful phone background.",
    imageUrl: "https://cdn.walzoo.com/Phone/Space/earth-from-space-night-lights-minimalist-phone.webp",
    category: 'Phone',
    subCategory: 'Space',
    width: 1080,
    height: 2340,
    extension: 'webp'
  },
  {
    id: 40,
    slug: "hot-air-balloons-winter-valley",
    title: "Winter Valley Hot Air Balloons",
    description: "Colorful hot air balloons drifting over a snowy winter river valley landscape. Stunning nature wallpaper for mobile.",
    imageUrl: "https://cdn.walzoo.com/Phone/Nature/hot-air-balloons-winter-river-valley-landscape-phone.webp",
    category: 'Phone',
    subCategory: 'Nature',
    width: 1080,
    height: 2340,
    extension: 'webp'
  },
  {
    id: 41,
    slug: "3d-glowing-neon-glass-cubes-art",
    title: "3D Glowing Neon Glass Cubes",
    description: "Intricate 3D geometric art featuring glowing neon glass cubes. A modern abstract aesthetic for your tablet.",
    imageUrl: "https://cdn.walzoo.com/Tablet/Abstract/3d-glowing-neon-glass-cubes-geometric-art-tablet.webp",
    category: 'Tablet',
    subCategory: 'Abstract',
    width: 2048,
    height: 2732,
    extension: 'webp'
  },
  {
    id: 42,
    slug: "new-york-city-skyline-night-reflection",
    title: "NYC Skyline Night Reflection",
    description: "The iconic New York City skyline illuminated at night with a perfect water reflection. Classic city landmark for tablets.",
    imageUrl: "https://cdn.walzoo.com/Tablet/Cities%20%26%20Landmarks/new-york-city-skyline-night-reflection-tablet.webp",
    category: 'Tablet',
    subCategory: 'Cities & Landmarks',
    width: 2048,
    height: 2732,
    extension: 'webp'
  },
  {
    id: 43,
    slug: "autumn-trees-misty-lake-reflection",
    title: "Misty Autumn Lake",
    description: "Vibrant autumn trees reflecting in a misty lake. Clean minimalist 4K wallpaper for your desktop.",
    imageUrl: `${R2_BASE_URL}/Desktop/Minimalist/colorful-autumn-trees-misty-lake-reflection-pc.webp`,
    category: 'Desktop',
    subCategory: 'Minimalist',
    width: 3840,
    height: 2160,
    extension: 'webp'
  },
  {
    id: 44,
    slug: "golden-hexagon-honeycomb-red-glow",
    title: "Golden Honeycomb Hexagon",
    description: "Futuristic golden honeycomb pattern with a subtle red glow. High-tech 4K background for desktop setups.",
    imageUrl: `${R2_BASE_URL}/Desktop/Technology/golden-honeycomb-hexagon-pattern-red-glow-pc.webp`,
    category: 'Desktop',
    subCategory: 'Technology',
    width: 3840,
    height: 2160,
    extension: 'webp'
  },
  {
    id: 45,
    slug: "colorful-rounded-blocks-abstract",
    title: "Colorful Rounded Blocks",
    description: "Abstract textured pattern of colorful rounded blocks. Modern digital art for your phone screen.",
    imageUrl: `${R2_BASE_URL}/Phone/Digital%20Art/textured-abstract-colorful-rounded-blocks-pattern-phone.webp`,
    category: 'Phone',
    subCategory: 'Digital Art',
    width: 1080,
    height: 2340,
    extension: 'webp'
  },
  {
    id: 46,
    slug: "western-cowboy-winter-forest",
    title: "Winter Cowboy Rider",
    description: "A cinematic scene of a western cowboy riding through a snowy winter forest. Epic gaming theme for mobile.",
    imageUrl: `${R2_BASE_URL}/Phone/Gaming/western-cowboy-riding-horse-winter-snow-forest-phone.webp`,
    category: 'Phone',
    subCategory: 'Gaming',
    width: 1080,
    height: 2340,
    extension: 'webp'
  },
  {
    id: 47,
    slug: "white-lion-cubs-hugging",
    title: "White Lion Cubs Hugging",
    description: "Heartwarming moment of two white lion cubs hugging in the grassland. Cute animal wallpaper for tablet.",
    imageUrl: `${R2_BASE_URL}/Tablet/Animals/white-lion-cubs-hugging-grassland-tablet.webp`,
    category: 'Tablet',
    subCategory: 'Animals',
    width: 2048,
    height: 2732,
    extension: 'webp'
  },
  {
    id: 48,
    slug: "emerald-sportscar-cherry-blossoms",
    title: "Emerald Sportscar & Cherry Blossoms",
    description: "Luxurious emerald green sportscar parked among blooming cherry blossoms. Stylish car background for tablets.",
    imageUrl: `${R2_BASE_URL}/Tablet/Cars/emerald-green-luxury-sportscar-cherry-blossoms-tablet.webp`,
    category: 'Tablet',
    subCategory: 'Cars',
    width: 2048,
    height: 2732,
    extension: 'webp'
  },
  {
    id: 49,
    slug: "winding-autumn-forest-path",
    title: "Winding Autumn Forest Path",
    description: "A peaceful winding path through an autumn forest with vibrant orange leaves and a rustic fence. High-quality 4K Seasons wallpaper.",
    imageUrl: "https://cdn.walzoo.com/Desktop/Seasons/winding-autumn-forest-path-orange-leaves-fence-pc.webp",
    category: 'Desktop',
    subCategory: 'Seasons',
    width: 3840,
    height: 2160,
    extension: 'webp'
  },
  {
    id: 50,
    slug: "basketball-court-sunlight-forest",
    title: "Forest Basketball Court",
    description: "An empty basketball court bathed in warm sunlight, surrounded by lush forest trees. Dynamic 4K sports background.",
    imageUrl: "https://cdn.walzoo.com/Desktop/Sports/empty-basketball-court-sunlight-forest-trees-pc.webp",
    category: 'Desktop',
    subCategory: 'Sports',
    width: 3840,
    height: 2160,
    extension: 'webp'
  },
  {
    id: 51,
    slug: "chinese-calligraphy-black-bg",
    title: "Artistic Chinese Calligraphy",
    description: "Elegant Chinese calligraphy set against a minimalist black background. Artistic anime-inspired phone wallpaper.",
    imageUrl: "https://cdn.walzoo.com/Phone/Anime/chinese-calligraphy-black-background-phone.webp",
    category: 'Phone',
    subCategory: 'Anime',
    width: 1080,
    height: 2340,
    extension: 'webp'
  },
  {
    id: 52,
    slug: "focus-on-your-goal-quote",
    title: "Focus On Your Goal",
    description: "Motivational 'Focus on your goal' quote with a textured background. Inspiring typography for your phone.",
    imageUrl: "https://cdn.walzoo.com/Phone/Quotes/focus-on-your-goal-motivational-texture-phone.webp",
    category: 'Phone',
    subCategory: 'Quotes',
    width: 1080,
    height: 2340,
    extension: 'webp'
  },
  {
    id: 53,
    slug: "urban-alleyway-graffiti-art",
    title: "Urban Graffiti Alleyway",
    description: "A vibrant urban alleyway filled with colorful graffiti art. A gritty yet artistic culture-themed tablet wallpaper.",
    imageUrl: "https://cdn.walzoo.com/Tablet/Culture/urban-alleyway-colorful-graffiti-art-tablet.webp",
    category: 'Tablet',
    subCategory: 'Culture',
    width: 2048,
    height: 2732,
    extension: 'webp'
  },
  {
    id: 54,
    slug: "fluffy-white-kitten-purple-eyes",
    title: "Fluffy White Kitten",
    description: "A cute fluffy white kitten with large, enchanting purple eyes. Adorable wallpaper for kids' tablets.",
    imageUrl: "https://cdn.walzoo.com/Tablet/Kids/fluffy-white-kitten-large-purple-eyes-tablet.webp",
    category: 'Tablet',
    subCategory: 'Kids',
    width: 2048,
    height: 2732,
    extension: 'webp'
  }
];

export const WALLPAPER_DATA: Record<Category, Wallpaper[]> = {
  'Home': [...MY_IMAGES].reverse(), 
  'Desktop': MY_IMAGES.filter(img => img.category === 'Desktop').reverse(),
  'Phone': MY_IMAGES.filter(img => img.category === 'Phone').reverse(),
  'Tablet': MY_IMAGES.filter(img => img.category === 'Tablet').reverse(),
};

export const ICON_PACK_DATA = [];